### ISSUE TITLE
Update sencha build process to current version of sencha Cmd.

### ISSUE THREAD

**Issue by nikobeer** [Max-Reger-Institut/Edirom-Online#1]
Our build process still remains at sencha Cmd 4.0.4.84. Testing a newer version does work with some error messages (see below). The result seems to be a problem with attribute value output when calculating (?) pixel positions (eg. in annotation grid view: `<img src="undefineddw=600&amp;amp;dh=600undefined" class="previewImg">`). Here the build process output:

`sencha:
     [exec] Sencha Cmd v7.3.0.19
     [exec] WARNING: An illegal reflective access operation has occurred
     [exec] WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/Users/niko/bin/Sencha/Cmd/7.3.0.19/lib/closure-compiler-v20180610.jar) to field java.io.File.path
     [exec] WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
     [exec] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
     [exec] WARNING: All illegal access operations will be denied in a future release
     [exec] [INF] Using GPL version of Ext JS version 4.2.1.883 from /Edirom-Online/ext.
     [exec] [INF] The implications of using GPL version can be found here (http://www.sencha.com/products/extjs/licensing).
     [exec] [INF] Processing Build Descriptor : default (production environment)
     [exec] Warning: Nashorn engine is planned to be removed from a future JDK release
     [exec] [INF] Loading compiler context
     [exec] [INF] Loading app json manifest...
     [exec] Warning: Nashorn engine is planned to be removed from a future JDK release
     [exec] Warning: Nashorn engine is planned to be removed from a future JDK release
     [exec] [WRN] C1005: Closure Compiler Warning (Unnecessary escape: '\{' is equivalent to just '{') -- /Edirom-Online/ext/src/data/reader/Reader.js:730:79
     [exec] [WRN] C1005: Closure Compiler Warning (Unnecessary escape: '\}' is equivalent to just '}') -- /Edirom-Online/ext/src/data/reader/Reader.js:730:109
     [exec] [WRN] C1005: Closure Compiler Warning (Unnecessary escape: '\[' is equivalent to just '[') -- /Edirom-Online/ext/src/ux/grid/FiltersFeature.js:768:59
     [exec] [WRN] C1005: Closure Compiler Warning (Unnecessary escape: '\]' is equivalent to just ']') -- /Edirom-Online/ext/src/ux/grid/FiltersFeature.js:768:67
     [exec] [WRN] C1005: Closure Compiler Warning (Unnecessary escape: '\[' is equivalent to just '[') -- /Edirom-Online/ext-ux/grid/FiltersFeature.js:718:59
     [exec] [WRN] C1005: Closure Compiler Warning (Unnecessary escape: '\]' is equivalent to just ']') -- /Edirom-Online/ext-ux/grid/FiltersFeature.js:718:67
     [exec] [INF] Writing output to file /Edirom-Online/build/temp/production/EdiromOnline/sencha-compiler/cmd-packages.js
     [exec] [WRN] C1005: Closure Compiler Warning (Unnecessary escape: '\{' is equivalent to just '{') -- /Edirom-Online/ext/src/data/reader/Reader.js:730:79
     [exec] [WRN] C1005: Closure Compiler Warning (Unnecessary escape: '\}' is equivalent to just '}') -- /Edirom-Online/ext/src/data/reader/Reader.js:730:109
     [exec] [WRN] C1005: Closure Compiler Warning (Unnecessary escape: '\[' is equivalent to just '[') -- /Edirom-Online/ext/src/ux/grid/FiltersFeature.js:768:59
     [exec] [WRN] C1005: Closure Compiler Warning (Unnecessary escape: '\]' is equivalent to just ']') -- /Edirom-Online/ext/src/ux/grid/FiltersFeature.js:768:67
     [exec] [WRN] C1005: Closure Compiler Warning (Unnecessary escape: '\[' is equivalent to just '[') -- /Edirom-Online/ext-ux/grid/FiltersFeature.js:718:59
     [exec] [WRN] C1005: Closure Compiler Warning (Unnecessary escape: '\]' is equivalent to just ']') -- /Edirom-Online/ext-ux/grid/FiltersFeature.js:718:67
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.panel.Panel.getHeightAuthority) -- /Edirom-Online/ext/src/panel/Panel.js:1341:48680
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.panel.Panel.initAria) -- /Edirom-Online/ext/src/panel/Panel.js:642:26581
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.panel.Panel.getWidthAuthority) -- /Edirom-Online/ext/src/panel/Panel.js:1333:48470
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.dom.Layer.afterFx) -- /Edirom-Online/ext/src/dom/Layer.js:423:12947
     [exec] [WRN] C1014: callParent has no target (me.callParent in Ext.dom.Layer.setWidth) -- /Edirom-Online/ext/src/dom/Layer.js:529:15649
     [exec] [WRN] C1014: callParent has no target (me.callParent in Ext.dom.Layer.setBounds) -- /Edirom-Online/ext/src/dom/Layer.js:564:16711
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.dom.Layer.setLeftTop) -- /Edirom-Online/ext/src/dom/Layer.js:446:13443
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.dom.Layer.setLocalXY) -- /Edirom-Online/ext/src/dom/Layer.js:456:13644
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.dom.Layer.setTop) -- /Edirom-Online/ext/src/dom/Layer.js:441:13333
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.dom.Layer.setLocalX) -- /Edirom-Online/ext/src/dom/Layer.js:451:13543
     [exec] [WRN] C1014: callParent has no target (me.callParent in Ext.dom.Layer.setHeight) -- /Edirom-Online/ext/src/dom/Layer.js:544:16075
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.dom.Layer.setLocalY) -- /Edirom-Online/ext/src/dom/Layer.js:461:13744
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.dom.Layer.setLeft) -- /Edirom-Online/ext/src/dom/Layer.js:436:13233
     [exec] [WRN] C1014: callParent has no target (me.callParent in Ext.dom.Layer.setSize) -- /Edirom-Online/ext/src/dom/Layer.js:514:15221
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.dom.Layer.beforeFx) -- /Edirom-Online/ext/src/dom/Layer.js:418:12861
     [exec] [WRN] C1014: callParent has no target (me.callParent in Ext.chart.series.Cartesian.combine) -- /Edirom-Online/ext/src/chart/series/Cartesian.js:127:4376
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.chart.series.Cartesian.clearCombinations) -- /Edirom-Online/ext/src/chart/series/Cartesian.js:133:4594
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.form.FieldAncestor.beforeDestroy) -- /Edirom-Online/ext/src/form/FieldAncestor.js:203:7682
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.form.field.TextArea.initAria) -- /Edirom-Online/ext/src/form/field/TextArea.js:286:9762
     [exec] [WRN] C1014: callParent has no target (me.callParent in Ext.grid.plugin.RowEditing.startEditByClick) -- /Edirom-Online/ext/src/grid/plugin/RowEditing.js:276:8983
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.rtl.dom.Element_position.setY) -- /Edirom-Online/ext/src/rtl/dom/Element_position.js:284:8745
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.rtl.dom.Element_position.setX) -- /Edirom-Online/ext/src/rtl/dom/Element_position.js:274:8437
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.rtl.dom.Element_position.setXY) -- /Edirom-Online/ext/src/rtl/dom/Element_position.js:279:8593
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.rtl.dom.Layer.rtlSetLocalY) -- /Edirom-Online/ext/src/rtl/dom/Layer.js:43:1223
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.rtl.grid.RowEditor.setButtonPosition) -- /Edirom-Online/ext/src/rtl/grid/RowEditor.js:27:982
     [exec] [WRN] C1014: callParent has no target (this.callParent in Ext.ux.TabCloseMenu.onBeforeDestroy) -- /Edirom-Online/ext/src/ux/TabCloseMenu.js:84:2119
     [exec] [INF] Processing data with CmdJavascriptCompressor
     [exec] [INF] JavaScript input level is NEXT and output level is ES5
     [exec] [INF] Writing concatenated output to file /Edirom-Online/build/production/EdiromOnline/app.js
     [exec] [INF] merging 302 input resources into /Edirom-Online/build/production/EdiromOnline/resources
     [exec] [INF] merged 0 resources into /Edirom-Online/build/production/EdiromOnline/resources
     [exec] [INF] merging 0 input resources into /Edirom-Online/build/production/EdiromOnline
     [exec] [INF] merged 0 resources into /Edirom-Online/build/production/EdiromOnline
     [exec] Warning: Nashorn engine is planned to be removed from a future JDK release
     [exec] [INF] writing content to /Edirom-Online/build/temp/production/EdiromOnline/slicer-temp/bootstrap.js
     [exec] [INF] appending content to /Edirom-Online/build/temp/production/EdiromOnline/slicer-temp/bootstrap.js
     [exec] [INF] appending content to /Edirom-Online/build/temp/production/EdiromOnline/slicer-temp/bootstrap.js
     [exec] [INF] appending content to /Edirom-Online/build/temp/production/EdiromOnline/slicer-temp/bootstrap.js
     [exec] [INF] appending content to /Edirom-Online/build/temp/production/EdiromOnline/slicer-temp/bootstrap.js
     [exec] [INF] writing sass content to /Edirom-Online/build/temp/production/EdiromOnline/slicer-temp/EdiromOnline-example.scss.tmp
     [exec] [INF] writing sass content to /Edirom-Online/build/temp/production/EdiromOnline/slicer-temp/config.rb
     [exec] [INF] executing compass using system installed ruby runtime
     [exec]    create EdiromOnline-example.css 
     [exec] [INF] Capturing theme image
     [exec] [INF] Capture complete
     [exec] [INF] Slicing images...
     [exec] [INF] Slicing complete - generated 193 images
     [exec] Warning: Nashorn engine is planned to be removed from a future JDK release
     [exec] [INF] writing content to /Edirom-Online/build/temp/production/EdiromOnline/slicer-temp/bootstrap.js
     [exec] [INF] appending content to /Edirom-Online/build/temp/production/EdiromOnline/slicer-temp/bootstrap.js
     [exec] [INF] appending content to /Edirom-Online/build/temp/production/EdiromOnline/slicer-temp/bootstrap.js
     [exec] [INF] appending content to /Edirom-Online/build/temp/production/EdiromOnline/slicer-temp/bootstrap.js
     [exec] [INF] appending content to /Edirom-Online/build/temp/production/EdiromOnline/slicer-temp/bootstrap.js
     [exec] [INF] writing sass content to /Edirom-Online/build/temp/production/EdiromOnline/sass/EdiromOnline-all.scss.tmp
     [exec] [INF] appending sass content to /Edirom-Online/build/temp/production/EdiromOnline/sass/EdiromOnline-all.scss.tmp
     [exec] [INF] appending sass content to /Edirom-Online/build/temp/production/EdiromOnline/sass/EdiromOnline-all.scss.tmp
     [exec] [INF] writing sass content to /Edirom-Online/build/temp/production/EdiromOnline/sass/config.rb
     [exec] [INF] executing compass using system installed ruby runtime
     [exec]    remove .sass-cache/ 
     [exec]    remove EdiromOnline-all.css 
     [exec]    create EdiromOnline-all.css 
     [exec] [INF] Preprocessing /Edirom-Online/build/production/EdiromOnline/resources/EdiromOnline-all.css to /Edirom-Online/build/production/EdiromOnline/resources/EdiromOnline-all.css
     [exec] [INF] Compressing /Edirom-Online/build/production/EdiromOnline/resources/EdiromOnline-all.css to /Edirom-Online/build/production/EdiromOnline/resources/EdiromOnline-all.css
     [exec] [INF] Preprocessing /Edirom-Online/build/production/EdiromOnline/resources/EdiromOnline-all_01.css to /Edirom-Online/build/production/EdiromOnline/resources/EdiromOnline-all_01.css
     [exec] [INF] Compressing /Edirom-Online/build/production/EdiromOnline/resources/EdiromOnline-all_01.css to /Edirom-Online/build/production/EdiromOnline/resources/EdiromOnline-all_01.css
     [exec] [INF] Preprocessing /Edirom-Online/build/production/EdiromOnline/resources/EdiromOnline-all_02.css to /Edirom-Online/build/production/EdiromOnline/resources/EdiromOnline-all_02.css
     [exec] [INF] Compressing /Edirom-Online/build/production/EdiromOnline/resources/EdiromOnline-all_02.css to /Edirom-Online/build/production/EdiromOnline/resources/EdiromOnline-all_02.css
     [exec] Warning: Nashorn engine is planned to be removed from a future JDK release
     [exec] [INF] Copying page resources to /Edirom-Online/build/production/EdiromOnline
     [exec] [INF] Building output markup to /Edirom-Online/build/production/EdiromOnline/index.html
     [exec] [INF] Writing content to /Edirom-Online/build/production/EdiromOnline/index.html`

**Comment by nikobeer** [comment]
OK: on macOS Big Sur (11.1) build with sencha Cmd 4.0.4.84 and openJDK (build 11.0.9+11) fails. So for now going with sencha Cmd 7.3.0.19 and live with the above mentioned problems in the resulting app.

Build output:

`-init:
[x-sencha-init] Initializing Sencha Cmd ant environment

BUILD FAILED
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.sencha.util.StringUtil.fromBase64(StringUtil.java:196)
	at com.sencha.security.KeyData.getPublicKey(KeyData.java:34)
	at com.sencha.security.Certificate.<init>(Certificate.java:338)
	at com.sencha.security.Certificate.load(Certificate.java:331)
	at com.sencha.security.CertificateFileStore$1.accept(CertificateFileStore.java:113)
	at java.base/java.io.File.listFiles(File.java:1305)
	at com.sencha.security.CertificateFileStore.loadDir(CertificateFileStore.java:109)
	at com.sencha.security.CertificateFileStore.<init>(CertificateFileStore.java:31)
	at com.sencha.tools.pkg.LocalRepository.loadCertificateStore(LocalRepository.java:867)
	at com.sencha.tools.pkg.LocalRepository.loadConfig(LocalRepository.java:922)
	at com.sencha.tools.pkg.LocalRepository.<init>(LocalRepository.java:97)
	at com.sencha.command.environment.WorkspaceRepository.getLocalRepository(WorkspaceRepository.java:262)
	at com.sencha.command.environment.WorkspaceRepository.getCatalog(WorkspaceRepository.java:241)
	at com.sencha.command.environment.WorkspaceRepository.resolvePackageModels(WorkspaceRepository.java:117)
	at com.sencha.command.environment.WorkspaceRepository.resolvePackageEnvironments(WorkspaceRepository.java:97)
	at com.sencha.command.environment.AppOrPackageEnvironment.getRequiredPackageEnvironments(AppOrPackageEnvironment.java:187)
	at com.sencha.command.environment.AppOrPackageEnvironment.getRequiredPackagesNoThemes(AppOrPackageEnvironment.java:248)
	at com.sencha.command.environment.AppOrPackageEnvironment.getRequiredPackageNamesNoThemes(AppOrPackageEnvironment.java:239)
	at com.sencha.command.environment.AppEnvironment$3.call(AppEnvironment.java:80)
	at com.sencha.command.environment.AppEnvironment$3.call(AppEnvironment.java:78)
	at com.sencha.command.environment.BuildEnvironment$3.call(BuildEnvironment.java:731)
	at com.sencha.util.Configuration.get(Configuration.java:61)
	at com.sencha.util.Configuration.each(Configuration.java:180)
	at com.sencha.util.Configuration.each(Configuration.java:223)
	at com.sencha.ant.InitTask.doExecute(InitTask.java:90)
	at com.sencha.ant.BaseAntTask.execute(BaseAntTask.java:32)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.Main.runBuild(Main.java:830)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1383)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1338)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1093)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 42 more

Total time: 3 seconds

BUILD FAILED
/Edirom-Online/.sencha/app/init-impl.xml:54: com.sencha.exceptions.BasicException: javax/xml/bind/DatatypeConverter
	at com.sencha.exceptions.BasicException.wrap(BasicException.java:51)
	at com.sencha.exceptions.BasicException.stealthify(BasicException.java:43)
	at com.sencha.exceptions.BasicException.raise(BasicException.java:35)
	at com.sencha.ant.BaseAntTask.execute(BaseAntTask.java:36)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.Main.runBuild(Main.java:830)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.sencha.util.StringUtil.fromBase64(StringUtil.java:196)
	at com.sencha.security.KeyData.getPublicKey(KeyData.java:34)
	at com.sencha.security.Certificate.<init>(Certificate.java:338)
	at com.sencha.security.Certificate.load(Certificate.java:331)
	at com.sencha.security.CertificateFileStore$1.accept(CertificateFileStore.java:113)
	at java.base/java.io.File.listFiles(File.java:1305)
	at com.sencha.security.CertificateFileStore.loadDir(CertificateFileStore.java:109)
	at com.sencha.security.CertificateFileStore.<init>(CertificateFileStore.java:31)
	at com.sencha.tools.pkg.LocalRepository.loadCertificateStore(LocalRepository.java:867)
	at com.sencha.tools.pkg.LocalRepository.loadConfig(LocalRepository.java:922)
	at com.sencha.tools.pkg.LocalRepository.<init>(LocalRepository.java:97)
	at com.sencha.command.environment.WorkspaceRepository.getLocalRepository(WorkspaceRepository.java:262)
	at com.sencha.command.environment.WorkspaceRepository.getCatalog(WorkspaceRepository.java:241)
	at com.sencha.command.environment.WorkspaceRepository.resolvePackageModels(WorkspaceRepository.java:117)
	at com.sencha.command.environment.WorkspaceRepository.resolvePackageEnvironments(WorkspaceRepository.java:97)
	at com.sencha.command.environment.AppOrPackageEnvironment.getRequiredPackageEnvironments(AppOrPackageEnvironment.java:187)
	at com.sencha.command.environment.AppOrPackageEnvironment.getRequiredPackagesNoThemes(AppOrPackageEnvironment.java:248)
	at com.sencha.command.environment.AppOrPackageEnvironment.getRequiredPackageNamesNoThemes(AppOrPackageEnvironment.java:239)
	at com.sencha.command.environment.AppEnvironment$3.call(AppEnvironment.java:80)
	at com.sencha.command.environment.AppEnvironment$3.call(AppEnvironment.java:78)
	at com.sencha.command.environment.BuildEnvironment$3.call(BuildEnvironment.java:731)
	at com.sencha.util.Configuration.get(Configuration.java:61)
	at com.sencha.util.Configuration.each(Configuration.java:180)
	at com.sencha.util.Configuration.each(Configuration.java:223)
	at com.sencha.ant.InitTask.doExecute(InitTask.java:90)
	at com.sencha.ant.BaseAntTask.execute(BaseAntTask.java:32)
	... 16 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1383)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1338)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1093)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 42 more
`

**Comment by cappelnord** [comment]
https://forum.sencha.com/forum/showthread.php?469869-ERR-javax-xml-bind-DatatypeConverter this suggests that it could maybe be fixed by downgrading Java to Version 8?

**Comment by cappelnord** [comment]
Als when it's cumbersome: Setting up a stable build environment in a VM (with older but trusty versions of the tools) could also be a workaround (for now).

**Comment by cappelnord** [comment]
Otherwise we at some point need to dissect the issue and see how/if it can be fixed :)
